In [ ]:
import torch
import numpy as np

## Tensor Initialization

In [ ]:
#Les tensors sont similaires aux arrays mais ils peuvent être utilisés sur le GPU.
#On peut créer des tensors directement à partir de données, le type des données est conservé.
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array) # On peut créer un tensor à partir d'un array numpy.
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
#On crée un tensor remplis de 1 de même shape que x_data.
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

#Ici on change le type de donnée en float, les données seront entièrement des uns.
x_ones = torch.ones_like(x_data, dtype=torch.float)
print(f"Ones Tensor float: \n {x_ones} \n")

#Ici on change le type de donnée en float, les données seront des valeurs aléatoire uniforme dans [0,1].
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor float: 
 tensor([[1., 1.],
        [1., 1.]]) 

Random Tensor: 
 tensor([[0.4183, 0.0968],
        [0.0047, 0.3690]]) 



In [ ]:
shape1 = (2, 3,) #2 lignes 3 colonnes
rand_tensor1 = torch.rand(shape1) #Valeur aléatoire uniforme dans [0,1] et shape (2,3)
ones_tensor1 = torch.ones(shape1) #Tensor de 1 avec shape (2,3)
zeros_tensor1 = torch.zeros(shape1) #Tensor de 0 avec shape (2,3)

shape2 = (4, 2,) #4 lignes 2 colonnes
rand_tensor2 = 2*torch.rand(shape2) + 1 #Valeur aléatoire uniforme dans [1,3] et shape (4,2)
ones_tensor2 = torch.ones(shape2, dtype=torch.int) #Tensor de 1 avec shape (4,2) et type int
zeros_tensor2 = torch.zeros(shape2) #Tensor de 0 avec shape (4,2)


#Print des tensors
print(f"Shape 1 (2,3) \n")

print(f"Random Tensor: \n {rand_tensor1} \n")
print(f"Ones Tensor: \n {ones_tensor1} \n")
print(f"Zeros Tensor: \n {zeros_tensor1} \n")

print(f"Shape 2 (4,2) \n")

print(f"Random Tensor: \n {rand_tensor2} \n")
print(f"Ones Tensor: \n {ones_tensor2} \n") #Les valeurs afficher sont bien des int
print(f"Zeros Tensor: \n {zeros_tensor2}")

Shape 1 (2,3) 

Random Tensor: 
 tensor([[0.5791, 0.0992, 0.6649],
        [0.3478, 0.4387, 0.0820]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Shape 2 (4,2) 

Random Tensor: 
 tensor([[1.4645, 2.2881],
        [2.7536, 2.0906],
        [2.4274, 2.5246],
        [2.2308, 1.5044]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32) 

Zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


## Tensor Attributes

In [ ]:
tensor = torch.rand(3, 4) #Valeur aléatoire uniforme dans [0,1] et de taille 3x4
print(f"Shape of tensor: {tensor.shape}") #On affiche la taille de notre tensor
print(f"Datatype of tensor: {tensor.dtype}") #On affiche le type de donnée dans notre tensor
print(f"Device tensor is stored on: {tensor.device}") #On vérifie sur quel apparail notre tensors est stocké (CPU, GPU)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

In [ ]:
# We move our tensor to the GPU if available
# Il faut vérifier qu'un GPU est utilisé sous google colab
print(torch.cuda.is_available())
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
print(f"Device tensor is stored on: {tensor.device}")

False
Device tensor is stored on: cpu


In [ ]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0 #On remplace toute la 2ème colonne par 0
print(tensor)

tensor[0,2:] += 2 #On rajoute 2 à la première ligne à partir de l'indice 2
print(tensor)

t1 = torch.cat([tensor, tensor, tensor], dim=1) #On concatene 3 tensors
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 3., 3.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 3., 3., 1., 0., 3., 3., 1., 0., 3., 3.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
#On multiplie élément par élément
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
#Même chose mais syntaxe différente
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 4., 4.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 4., 4.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#Multiplication matriciel
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
#Même chose mais syntaxe différente
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[9., 5., 5., 5.],
        [5., 3., 3., 3.],
        [5., 3., 3., 3.],
        [5., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[9., 5., 5., 5.],
        [5., 3., 3., 3.],
        [5., 3., 3., 3.],
        [5., 3., 3., 3.]])


In [ ]:
print(tensor, "\n")
tensor.add_(5) #On rajoute 5 à toutes les valeurs.
print(tensor)

tensor([[1., 0., 2., 2.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 7., 7.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy

In [ ]:
t = torch.ones(5) # On crée un tensor de taille 5 remplis de 1
print(f"t: {t}")
n = t.numpy() # On crée un array à partir du tensor t
print(f"n: {n} \n")

#Quand on crée un array à partir d'un tensor, les deux variables ont la même allocation mémoire.
#Donc si on modifie l'un, on modifie l'autre aussi.
t.add_(1)
print("Après modification:")
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.] 

Après modification:
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
n = np.ones(5) #On crée un array de taille 5 remplis de 1
t = torch.from_numpy(n) # On crée un tensor à partir de l'array n

#La réciproque est vraie aussi, i.e créer un tensor à partir d'un array allouera le même espace mémoire.
#Donc si on modifie l'un, on modifie l'autre aussi.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
